student_name = input("Enter your name: ")
course_name = input("Enter the course name: ")
age = int(input("Enter your age: "))
print("Student: " + student_name)
print("Course: " + course_name)
print("Age: " + int(age))